<?php
/** @var Magento\Backend\Block\Template $block */

/** @var Ankitdev\PoNumber\Model\Data\PoNumber $PoNumber */
$PoNumber = $block->getOrderPoNumber();
?>
<?php if($PoNumber): ?>
    <section class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Other information') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="order-information">
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Purchase order no.') ?></span></strong>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($PoNumber->getCheckoutPurchaseOrderNo()); ?>
                    </div>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
